apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-role-binding
subjects:
- namespace: default 
  kind: ServiceAccount
  name: backend-service-account 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-writer
