name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  image_name: backend
  repository: pypsa-workflow
  registry: europe-central2-docker.pkg.dev

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Push to GCR GitHub Action
      uses: RafikFarhad/push-to-gcr-github-action@v4.1
      with:
        gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        registry: ${{ env.registry }}
        project_id: ${{ secrets.GKE_PROJECT }}
        image_name: ${{ env.repository }}/${{ env.image_name }}
        image_tag: ${{ github.sha }},latest
        dockerfile: Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCLOUD_SERVICE_KEY }}'
    - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_ZONE }}
    - name: Deploy newest image to GKE
      run: |
        sed 's/${_IMAGE}/${{ env.registry }}/${{ env.repository }}/${{ env.image_name }}:${{ github.sha }}/g' \
          manifests/deployment.yaml.tmpl > manifests/deployment.yaml
        kubectl apply -f manifests
